apiVersion: v1
kind: Secret
metadata:
  name: minio-secret                   # Secret 명
  annotations:
    serving.kserve.io/s3-endpoint: minio-service.kubeflow:9000  # 설치된 Minio 서비스 endpoint
    serving.kserve.io/s3-usehttps: "0"   # http를 사용하지 않음 (설치된 Minio 설정)
    serving.kserve.io/s3-verifyssl: "0"  # ssy verify 하지 않음 (설치된 Minio 설정)
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-useanoncredential: "false"  # anonymous인 경우 true로 설정
data:
  AWS_ACCESS_KEY_ID: bWluaW8= # replace with your base64 encoded s3 credential
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM= # replace with your base64 encoded s3 credential
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa                          # ServiceAccount 명
secrets:
- name: minio-secret                       # 이 ServiceAccount가 사용할 Secret (위에서 생성한 Secret)

