FROM tensorflow/tensorflow:latest-py3
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y ffmpeg libsm6 libxext6 

RUN  pip3 install --upgrade pip && \
     pip install \
        sklearn \
        opencv-python \
        pillow \
        minio