FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full:v1.5.0-rc.1
USER root
RUN apt update \
 && apt install libgl1-mesa-glx -y

USER jovyan
RUN pip install opencv-python imutils 
