apiVersion: v1
kind: Secret
metadata:
  name: minio-secret   # Secret 명
  namespace: myspace   # Secret이 설치될 Namespace
  annotations:
    serving.kubeflow.org/s3-endpoint: minio-service.kubeflow:9000  # 설치된 Minio 서비스 endpoint
    serving.kubeflow.org/s3-usehttps: "0"   # http를 사용하지 않음 (설치된 Minio 설정)
    serving.kubeflow.org/s3-verifyssl: "0"  # ssy verify 하지 않음 (설치된 Minio 설정)
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kfserving-sa   # ServiceAccount 명
  namespace: myspace   # ServiceAccount가 설치될 Namespace
secrets:
- name: minio-secret   # 이 ServiceAccount가 사용할 Secret (위에서 생성한 Secret)
